
class DataIngestionArtifact:
    pass

## meaning of 3 dots is pass
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...