
class DataIngestionConfig:
    pass

## meaning of 3 dots is pass
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...